### PR TITLE
Chores + fixes

### PR DESCRIPTION
**Pull request by piranna**
Update of dependencies, clean-ups, and fixes for generating binaries.

### CODE REVIEW

**Comment by piranna** [comment]
Tested myself, and CI is passing. Can this be merged and published?

**Comment by piranna** [comment]
Any update on this?

**Comment by OsamaAbbas** [comment]
Merged. I will do some minor changes and publish a new version to npm. Thank you.

**Comment by piranna** [comment]
> Merged. I will do some minor changes and publish a new version to npm. Thank you.

Welcome :-)

**Comment by OsamaAbbas** [comment]
Published to npm.

However, while the tests passed on Linux, two tests (related to Electron) won't run on Windows. If you have the chance to look into it, I'd really appreciate it. I will try to look into it later, but I'm stuck with my MSc thesis right now, with no free time or energy to deal with Windows (and Electron) :) .

**Comment by piranna** [comment]
I don't have access to a Windows machine, sorry... :-/ What issues do you have? Maybe some Windows machines can be added to CI so tests pass there too?

**Pull request merged**
