### PR TITLE
Export module values in loader & clean formating

### PR DESCRIPTION
**Pull request by piranna**
This allow to `require` and `import` values exported in the `*.jsc` files directly by using the default loader, without needing a custom one.

### CODE REVIEW

**Comment by OsamaAbbas** [comment]
Could you please remind me of what this pull request aims for? Especially the `import` part. Does this allow the `index.loader.js` file to be imported using the `import` keyword?

**Comment by piranna** [comment]
> Could you please remind me of what this pull request aims for? Especially the `import` part. Does this allow the `index.loader.js` file to be imported using the `import` keyword?

If you means about the injected code, is to allow to export the contend of the module, so yes, both with `import` and with `require` :-)

The last commit I've just added is to fix a bug I've seen when using a file extension different from `.js`, in my case `.cjs`, that has an extra character.

**Comment by piranna** [comment]
I've added some tests to verify and ensure the module exports are accesible, and also improved the examples in the `README`.

CommonJS modules are already importable by ESM by default, the improved checks in the loader is to ensure the `default` value is the one exported like a CommonJS, since they need to be like this to be included in the snapshot, instead of return a `{default}` object in case it was transpiled with babel or similar.

I've also added the generated `package-lock.json` file, but can remove it if you want.

What does needs this to be reviewed and merged?

**Comment by piranna** [comment]
I've added support to create a ESM loader, still it's not possible to create bytenodes of ESM modules, but if you create a CommonJS bundle from them for example using Webpack or rollup or something like this, now it's possible to export the original named exports.

**Comment by piranna** [comment]
Thank you :-)

**Comment by OsamaAbbas** [comment]
No, thank you for your work. I apologize as well for the late response.

I will publish the new version now to npm.

**Comment by piranna** [comment]
> I will publish the new version now to npm.

Awesome

**Pull request merged**
